In [1]:
import rasterio
import geopandas as gpd
import numpy as np
import pandas as pd

from rasterstats import zonal_stats
from rasterio.warp import reproject, Resampling
from rasterio.mask import mask

from pathlib import Path

In [2]:
src_dir = Path('~').expanduser() / "OneDrive - Stichting Deltares/Tiaravanni Hermawan's files - Egypt/04_Data/2026_data/"

In [3]:
population_dir = src_dir / 'demographic 2022'
population_files_f = list(population_dir.glob('egy_f*.tif'))
population_files_m = list(population_dir.glob('egy_m*.tif'))

population_files_f.sort()
population_files_m.sort()

with rasterio.open(population_files_f[0], 'r') as src:
    nodata = src.nodata

classification_file = src_dir / "EGY_DUG_2022_GRID_L1_R2025A_v1.tif"

In [6]:
com_gdf = gpd.read_file(src_dir / 'Final2_Command_Area.shp')
com_gdf = com_gdf.to_crs("EPSG:4326")

com_gdf_f = com_gdf.copy()
com_gdf_m = com_gdf.copy()

com_gdf_f['gender'] = 'female'
com_gdf_m['gender'] = 'male'

In [9]:
with rasterio.open(population_files_f[0]) as pop_src:
    population_shape = pop_src.shape
    transform = pop_src.transform
    crs = pop_src.crs

with rasterio.open(classification_file) as cls_src:
    classification = np.empty(population_shape, dtype=np.uint8)

    reproject(
        source=rasterio.band(cls_src, 1),
        destination=classification,
        src_transform=cls_src.transform,
        src_crs=cls_src.crs,
        dst_transform=transform,
        dst_crs=crs,
        dst_shape=population_shape,
        resampling=Resampling.nearest,
    )

for population_file in population_files_f:
    col = population_file.stem
    age_code = int(col.split("_")[2])
    with rasterio.open(population_file) as pop_src:
        population = pop_src.read(1)

        masked_pop = np.where(classification == 1, population, pop_src.nodata)

        stats = zonal_stats(
            com_gdf_f,
            masked_pop,
            affine=pop_src.transform,
            stats=["sum"],
            nodata=pop_src.nodata,
        )

    com_gdf_f[age_code] = [s["sum"] for s in stats]

for population_file in population_files_m:
    col = population_file.stem
    age_code = int(col.split("_")[2])
    with rasterio.open(population_file) as pop_src:
        population = pop_src.read(1)

        masked_pop = np.where(classification == 1, population, pop_src.nodata)

        stats = zonal_stats(
            com_gdf_m,
            masked_pop,
            affine=pop_src.transform,
            stats=["sum"],
            nodata=pop_src.nodata,
        )

    com_gdf_m[age_code] = [s["sum"] for s in stats]

/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:24: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:24: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:24: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:24: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:24: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:24: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:24: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:24: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:24: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:24: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:24: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:24: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:24: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:24: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:24: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:24: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:24: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:24: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:24: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:24: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:42: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:42: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:42: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:42: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:42: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:42: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:42: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:42: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:42: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:42: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:42: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:42: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:42: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:42: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:42: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:42: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:42: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:42: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:42: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)
/var/folders/1z/6xp0rndx2nqc7qx263rv42fh0000gn/T/ipykernel_69841/4038873482.py:42: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  population = pop_src.read(1)

In [10]:
com_gdf_f

,OBJECTID,Name,Shape_Leng,Shape_Area,Feddan,geometry,gender,0,1,5,...,45,50,55,60,65,70,75,80,85,90
0,1,الرشيدية_ومباشر غرب رشيد,121389.174241,3.754359e+08,89389.50,"POLYGON ((30.34442 31.38367, 30.3449 31.38464,...",female,166.152542,706.409363,942.714905,...,434.482605,353.727966,298.813049,242.739899,176.233856,113.666733,60.945129,27.218948,10.717461,2.499122
1,2,الرياح البحيرى,379980.523243,1.387385e+09,330330.00,"POLYGON ((30.49714 31.11192, 30.52423 31.12877...",female,455.005432,1934.483643,2417.553223,...,1182.377686,984.814453,858.670166,667.587280,544.712341,354.474884,196.728470,95.171234,37.487766,7.334262
2,6,الخيام,164484.927752,2.457438e+08,58510.40,"POLYGON ((32.06055 26.1862, 32.0578 26.18392, ...",female,61.188511,260.146667,367.564819,...,111.518036,86.576302,79.410530,65.625351,58.221779,32.626350,16.710918,8.581465,3.614874,0.719920
3,7,نجع حمادى الغربية,541735.552974,1.950372e+09,464374.00,"MULTIPOLYGON (((32.13347 26.10908, 32.13595 26...",female,403.760681,1716.613647,2334.558105,...,762.321960,645.818848,582.536865,530.556152,440.228607,304.986145,166.034912,72.018463,25.935791,4.928016
4,8,نجع حمادى الشرقية,385861.370984,6.143672e+08,146278.00,"POLYGON ((31.00797 27.35792, 31.01181 27.35664...",female,133.250046,566.520752,752.499695,...,232.708069,199.569122,172.371094,157.693146,125.948807,86.243027,47.949894,21.482477,8.137091,1.687006
5,9,الكلابية,334344.834772,7.479556e+08,178085.00,"POLYGON ((32.31197 26.10202, 32.31112 26.10345...",female,185.482407,706.473389,1022.231079,...,389.756653,318.597382,296.302368,269.977722,230.576965,171.050507,109.386398,64.892075,46.014259,30.974676
6,11,ترعة الصف,247397.493839,4.899687e+08,116659.00,"POLYGON ((31.29589 29.95965, 31.29888 29.95779...",female,158.538620,674.036621,877.546204,...,263.297638,221.140656,186.517456,153.753372,105.458649,70.299362,38.645424,16.862133,6.352654,1.365777
7,12,البحر الصغير,169102.077473,6.934083e+08,165097.00,"MULTIPOLYGON (((31.66716 31.20426, 31.66469 31...",female,297.061462,1262.975342,1664.896240,...,770.653320,635.757690,548.302368,451.690857,381.235870,235.719299,129.364166,66.348206,28.615200,6.436092
8,13,النجايل,89164.070500,1.617347e+08,38508.30,"POLYGON ((31.05187 30.31133, 31.05326 30.30991...",female,27.874578,118.510429,156.901382,...,59.559044,49.929466,45.093815,36.026752,28.952694,19.100607,11.186577,5.505428,2.034404,0.328440
9,14,قنال العنانية,69567.786666,6.687478e+07,15922.60,"MULTIPOLYGON (((31.77007 31.39485, 31.77001 31...",female,8.712364,37.041119,47.490917,...,27.343409,25.596369,21.652779,17.943979,11.429063,7.042558,3.772265,1.665610,0.663443,0.164242
10,15,البلامون _ الساحل,248901.403537,5.682803e+08,135305.00,"POLYGON ((31.80117 31.47201, 31.80155 31.469, ...",female,205.340561,873.018799,1109.111206,...,535.536011,435.901184,372.270081,284.132019,237.649933,145.582321,77.867676,38.769985,16.133699,3.467552
11,16,الشرقاوية,120670.195430,5.983739e+08,142470.00,"POLYGON ((31.60361 30.55526, 31.60585 30.5525,...",female,90.806595,386.069763,509.856232,...,189.239258,162.154907,141.296234,116.488152,100.289879,66.939682,38.946655,19.454578,7.479238,1.309359
12,17,البوهية,128027.331374,5.657738e+08,134708.00,"POLYGON ((31.4718 30.76672, 31.47167 30.76694,...",female,214.010834,909.879883,1165.932495,...,543.532471,454.835693,401.068726,325.043091,295.205017,188.080322,104.822815,53.867237,22.258234,4.473686
13,18,بحر شبين,227695.614642,1.304927e+09,310697.00,"POLYGON ((31.16745 30.72426, 31.16743 30.72426...",female,480.871918,2044.455811,2656.049316,...,1334.246216,1142.608398,1011.628845,806.400635,696.097351,434.065186,239.310898,120.764175,48.691025,9.159554
14,19,بحر مويس,281979.844735,1.843466e+09,438920.00,"MULTIPOLYGON (((31.60027 30.55561, 31.60072 30...",female,570.943970,2427.403076,3245.518311,...,1352.566772,1047.704712,950.028870,753.986328,679.705750,404.058228,213.226898,108.612556,44.798458,8.807220
15,20,أسوان,755358.494757,1.448439e+09,344866.00,"MULTIPOLYGON (((32.92678 24.74431, 32.92567 24...",female,436.519165,1855.890137,2698.328613,...,1215.183228,1030.422363,908.921143,794.158325,596.056274,506.147156,323.987701,143.238312,51.029404,9.759441
16,21,الرنان الرئيسي,109003.972620,1.746415e+08,41581.30,"POLYGON ((32.49228 26.11167, 32.49504 26.11138...",female,60.222080,256.037781,369.978546,...,140.161682,120.275970,107.575539,98.818024,80.724777,62.158817,35.846405,15.531897,5.840317,1.301422
17,22,زمام اصفون,242292.235317,3.246991e+08,77309.30,"POLYGON ((32.64874 26.17484, 32.65518 26.17136...",female,95.579758,406.363220,597.927979,...,259.160889,201.898087,180.440460,159.613251,137.833755,113.277618,70.794060,32.595741,12.054259,2.311754
18,23,زمام الرمادي,103284.777776,2.262998e+08,53880.90,"POLYGON ((32.48669 25.48296, 32.50433 25.48022...",female,78.341965,333.076263,515.421631,...,188.536560,159.201172,135.082336,117.024872,95.031906,82.711143,50.174538,20.158848,6.447834,1.070762
19,24,زمام الكلابية القديمة,45239.055900,4.359444e+07,10379.60,"POLYGON ((32.57463 25.37824, 32.57936 25.36845...",female,37.695393,160.264252,248.002213,...,90.717049,76.601936,64.996788,56.308201,45.726006,39.797684,24.142235,9.699732,3.102488,0.515232
20,25,ابوحمار,35283.229044,5.976739e+07,14230.30,"POLYGON ((32.14171 26.16976, 32.14454 26.16278...",female,6.504301,27.653423,38.731010,...,13.048768,11.246913,9.153958,9.175508,7.121991,4.986291,3.023461,1.393449,0.494479,0.083260
21,26,الرنان الشرقي_بخانس,71339.871393,1.535572e+08,36561.20,"POLYGON ((32.05693 26.15217, 32.09029 26.12327...",female,27.354633,116.299850,164.713577,...,58.970783,50.871201,42.956238,40.802223,31.044735,23.555319,13.842299,5.811048,1.985224,0.359613
22,27,مباشر نيل,440607.015302,2.347692e+08,55897.40,"MULTIPOLYGON (((30.89034 27.41556, 30.89197 27...",female,124.658112,529.992310,727.582458,...,239.327179,198.597946,188.577744,150.110260,164.905533,99.300018,50.657330,25.994318,10.386831,1.760001
23,28,عمر بك,71886.744291,1.007574e+08,23989.90,"POLYGON ((31.22036 30.84091, 31.21932 30.84001...",female,47.734177,202.944733,257.041595,...,124.173347,106.332222,92.988525,74.810043,61.511909,41.055695,24.242054,12.367162,4.981458,0.958652
24,29,جنابية دهتورة,19519.801737,1.079042e+07,2569.15,"POLYGON ((31.21967 30.80897, 31.22057 30.80733...",female,2.107141,8.958635,11.452351,...,5.259958,4.441752,3.866358,3.181545,2.863311,1.951407,1.138406,0.573616,0.225014,0.040857
25,30,العطف,116190.657305,4.933201e+08,117457.00,"POLYGON ((31.20182 30.75551, 31.2016 30.7548, ...",female,199.207260,846.941833,1123.424316,...,490.593689,429.432098,377.272461,298.556610,262.897247,176.868195,105.540359,55.798576,22.886713,4.306966
26,31,البحر الصعيدي,69542.655002,1.913176e+08,45551.80,"POLYGON ((30.67002 31.40261, 30.67786 31.39477...",female,72.254128,307.193329,408.286743,...,193.325104,145.654434,132.807220,100.193924,90.222969,53.600330,24.847317,10.812752,4.142046,0.860274
27,32,خليج القني,20435.139266,1.820244e+07,4333.91,"POLYGON ((30.56246 31.28819, 30.55488 31.2798,...",female,5.786104,24.600006,32.652443,...,13.542770,10.684528,9.779079,7.796566,5.841316,3.935415,2.145129,0.960122,0.369054,0.079497
28,33,بحر بسنديلة _ بلقاس _ تيرة,236771.991064,1.818626e+09,433006.00,"POLYGON ((31.40589 31.13072, 31.38769 31.13271...",female,1186.655273,5045.139648,6673.832031,...,3232.881104,2499.113281,2152.047119,1677.132080,1476.130127,833.351807,432.689301,222.558243,93.781998,19.000051
29,34,السلام,304083.244938,9.971843e+08,237425.00,"POLYGON ((31.79847 31.28267, 31.79923 31.2797,...",female,598.714417,2545.472168,3399.503418,...,1217.909180,926.143799,806.464355,611.193909,478.535919,269.413574,136.441711,67.231491,28.403362,6.932760
30,35,الباجورية,228446.895459,8.882516e+08,211488.00,"POLYGON ((30.91432 31.08777, 30.91424 31.08778...",female,307.173767,1305.969482,1678.073730,...,885.884949,725.918640,653.988892,526.243774,430.700043,260.528931,138.423279,67.120171,26.918238,5.438065
31,36,دروة وراضى,72970.788021,5.093019e+07,12126.20,"POLYGON ((31.09876 30.37619, 31.09747 30.37447...",female,4.920321,20.919033,28.155825,...,11.347280,10.018546,8.832819,7.056526,6.209965,4.392954,2.636673,1.323631,0.508670,0.089260
32,37,الباسوسية,127801.857000,2.623758e+08,62470.40,"POLYGON ((31.34344 30.47083, 31.34182 30.4687,...",female,45.961563,195.408417,251.673126,...,102.810287,88.956421,79.345718,64.618546,53.856323,37.052990,21.315033,10.150572,3.805448,0.676592
33,38,أبو المنجا,110830.420956,2.991833e+08,71234.10,"MULTIPOLYGON (((31.11555 30.31566, 31.11587 30...",female,40.628880,172.736115,222.852783,...,82.550171,69.828568,60.117508,46.018085,33.786060,23.386444,13.223560,5.944942,2.198048,0.423442
34,39,ترعة البستان,132924.732070,8.413742e+08,200327.00,"POLYGON ((30.37607 30.61018, 30.44921 30.58266...",female,724.313477,3079.465088,4202.204590,...,1680.660400,1223.056152,1041.799438,727.798828,524.986694,292.321899,154.862167,82.466644,37.669685,9.806845
35,40,ترعة النصر,348502.131941,1.466091e+09,349069.00,"POLYGON ((29.70778 30.83411, 29.71036 30.83311...",female,1239.746094,5270.856934,7445.234375,...,2515.388184,1704.605225,1374.699463,991.338684,632.429749,340.146545,157.776047,70.400040,31.010998,11.261295
36,41,الرياح الناصرى,189154.586343,4.032182e+08,96004.30,"POLYGON ((30.67922 30.70454, 30.67999 30.70373...",female,394.582581,1677.591553,2106.641846,...,937.568237,718.375488,660.555359,505.907440,381.839355,224.447235,123.314713,62.594955,25.207552,4.716177
37,42,ترعة سيناء,228408.192093,6.009114e+08,143074.00,"POLYGON ((32.32711 30.57756, 32.35132 30.67114...",female,239.815079,1019.593567,1423.849365,...,469.247406,356.571228,290.033142,213.257202,148.985779,92.535782,50.689514,25.539196,12.326253,4.177166
38,43,ترعة المنايف,81242.775718,3.968343e+08,94484.30,"POLYGON ((32.18285 30.56816, 32.19248 30.56523...",female,115.498734,491.050232,641.733398,...,252.262497,213.255524,170.398331,126.400238,92.197769,64.746071,38.105782,18.187632,7.332279,1.655560
39,44,ترعة بورسعيد,158218.180406,1.998280e+08,47578.10,"POLYGON ((32.30828 31.0238, 32.30846 31.01846,...",female,107.591904,457.433624,597.231079,...,207.278412,168.991333,129.234970,102.486938,73.981773,46.404697,25.328541,12.184102,5.420906,1.603491
40,45,ترعة السويس,241200.663414,4.279141e+08,101884.00,"POLYGON ((32.28471 30.55316, 32.28841 30.54964...",female,280.369812,1192.010498,1505.489624,...,536.589111,472.108795,363.686676,284.665833,182.124039,131.540421,77.808083,35.649372,15.118762,4.510388
41,46,ترعي الصالحية و السعيدية,177227.006184,1.058180e+09,251948.00,"POLYGON ((32.12755 30.86196, 32.12402 30.81785...",female,757.453979,3220.363770,4285.594727,...,1627.870972,1281.573486,1126.075317,908.441284,761.355591,467.259247,271.889465,147.587448,61.324917,11.528805
42,47,ترعة الإسماعيلية,358672.555488,1.657309e+09,394597.00,"POLYGON ((31.73509 30.68554, 31.73475 30.68331...",female,749.225342,3185.375977,4271.256836,...,1499.950684,1239.424194,993.813110,770.085815,606.519287,397.740479,217.005341,101.420593,40.337212,8.883177
43,48,الرياح التوفيقى,181335.427857,5.172151e+08,123146.00,"POLYGON ((31.34582 30.87346, 31.34609 30.8711,...",female,141.591095,601.983154,795.966736,...,345.685699,290.662018,262.804993,207.613525,194.755249,132.235352,79.325424,42.498199,17.021870,2.916397
44,49,بحر طناح,116242.118633,3.425843e+08,81567.70,"POLYGON ((31.89942 31.0746, 31.89817 31.0744, ...",female,111.633026,474.614624,625.313232,...,293.765656,254.023499,215.697205,169.185303,153.995056,98.952103,54.895889,28.767727,12.565590,2.826313
45,50,المنصورية,86295.515439,2.406144e+08,57289.10,"POLYGON ((31.41496 31.06874, 31.4152 31.06811,...",female,72.384430,307.746826,394.420288,...,184.235901,157.860291,136.219345,105.802444,97.341934,66.475166,40.714027,22.341686,9.196453,1.623841
46,51,الشرقاوية_ من المنصورية,146848.436093,2.840497e+08,67630.90,"POLYGON ((31.76416 31.39144, 31.76462 31.39329...",female,102.292374,434.902618,564.119141,...,272.742828,224.437653,191.749542,154.442947,130.928925,82.589401,45.292892,22.755566,9.676483,2.204328
47,52,النوبارية,540522.768222,2.392990e+09,569759.00,"POLYGON ((29.8793 31.05455, 29.87992 31.05451,...",female,1523.273315,6476.290039,8377.999023,...,3266.625488,2476.698242,2167.509521,1593.034058,1140.840576,658.140259,344.138977,169.215591,70.712845,15.825728
48,53,المحمودية,258304.418666,1.203503e+09,286548.00,"POLYGON ((30.05393 31.29429, 30.05232 31.29239...",female,248.493103,1056.484619,1430.197998,...,639.872925,481.387573,416.658875,329.872375,255.953430,149.046600,79.517418,39.427734,15.823758,3.031392
49,54,ميت يزيد,204307.451596,1.118941e+09,266414.00,"POLYGON ((30.96521 31.46005, 30.96581 31.45477...",female,473.611115,2013.587280,2590.400879,...,1285.923950,1015.651917,898.023193,674.836182,596.847168,324.349365,155.030731,76.530197,32.951622,7.455082
50,55,الرياح العباسى,171993.414128,5.345701e+08,127279.00,"POLYGON ((31.40485 31.12397, 31.40398 31.11813...",female,184.130768,782.843262,1004.073975,...,493.689209,418.450531,358.195374,279.604370,234.535919,146.462845,77.913773,37.055283,14.570520,2.893597
51,56,زمام الرشدية_وسط الدلتا,110445.263979,2.196591e+08,52299.80,"MULTIPOLYGON (((30.40455 31.47208, 30.42761 31...",female,225.004822,956.621582,1269.758301,...,526.638672,415.490814,380.280121,303.186584,227.152802,153.037537,83.417763,37.336311,14.351597,3.091261
52,57,الرياح المنوفى,217246.533904,7.091952e+08,168856.00,"POLYGON ((30.84543 30.81231, 30.8435 30.7935, ...",female,152.662949,649.055725,829.196167,...,384.095459,337.149109,314.957520,249.505432,214.310089,136.408798,78.080734,40.982212,17.012455,3.275118
53,58,الابراهيمية,862976.326243,2.632504e+09,626787.00,"POLYGON ((30.72474 27.87707, 30.73037 27.87828...",female,860.066772,3656.631836,5006.846680,...,1595.600586,1343.924072,1256.517334,1013.070923,1082.031006,672.725037,348.957062,177.169006,71.531006,12.693132
54,59,بحر حسن واصف,431221.584178,7.670328e+08,182627.00,"MULTIPOLYGON (((30.50862 29.19402, 30.50706 29...",female,313.776489,1331.298096,1785.666870,...,540.205383,422.434204,379.769379,326.171326,316.351440,216.130630,122.749992,61.631947,24.739548,5.191412
55,60,البحر اليوسفي_الفيوم,247492.890070,1.117079e+09,265971.00,"POLYGON ((30.96891 29.23009, 30.97392 29.22245...",female,306.587952,1303.478271,1756.018311,...,527.717896,421.737427,381.255768,314.867920,286.808197,190.879837,105.265869,51.024422,19.854937,3.727730
56,62,ترعة سري باشا,285344.080271,4.608900e+08,109736.00,"POLYGON ((30.72474 27.87707, 30.72447 27.87964...",female,153.913513,654.373596,902.354553,...,307.208862,248.369217,235.791656,188.318329,194.047241,115.475685,59.788685,30.708963,12.104425,2.012207
57,63,ترعة الشيخ جابر,148008.629916,6.495025e+08,154643.00,"POLYGON ((32.31723 31.01515, 32.31703 31.02067...",female,222.682327,946.750549,1322.713379,...,422.477905,308.612610,255.148438,185.172501,132.700714,79.393311,43.482632,23.608768,12.568623,4.947841
58,65,البحر اليوسفي,600629.783332,1.055013e+09,251194.00,"POLYGON ((30.96925 29.19997, 30.97048 29.19902...",female,633.668396,2694.082275,3709.341064,...,1172.985352,946.246399,925.695923,720.135986,776.992920,475.516998,245.702026,128.240906,52.882965,9.516237
59,77,ترعة الجيزة,353243.598171,6.138948e+08,146165.00,"POLYGON ((31.05675 30.21855, 31.05761 30.21856...",female,155.191162,659.804810,869.626404,...,282.997162,236.358917,202.747757,163.753174,127.874641,85.168007,44.816620,19.467035,7.234604,1.417711

In [33]:
demographic_df = pd.read_excel("/Users/hemert/OneDrive - Stichting Deltares/Tiaravanni Hermawan's files - Egypt_ERF_data/data_correlation.xlsx", sheet_name="rural_gender_demographic")

In [34]:
demographic_gdf_f = com_gdf_f.T.iloc[7:]
demographic_gdf_m = com_gdf_m.T.iloc[7:]

demographic_gdf = pd.concat([demographic_gdf_f, demographic_gdf_m], axis=0)

In [35]:
demographic_gdf.columns = com_gdf['OBJECTID']

In [36]:
excel_df = pd.concat([demographic_df, demographic_gdf.reset_index()], axis=1).drop(columns="index")
excel_df

,gender,Code,Min age,Max age,1,2,6,7,8,9,...,55,56,57,58,59,60,62,63,65,77
0,female,0,0,0.99,166.152542,455.005432,61.188511,403.760681,133.250046,185.482407,...,184.130768,225.004822,152.662949,860.066772,313.776489,306.587952,153.913513,222.682327,633.668396,155.191162
1,female,1,1,4.00,706.409363,1934.483643,260.146667,1716.613647,566.520752,706.473389,...,782.843262,956.621582,649.055725,3656.631836,1331.298096,1303.478271,654.373596,946.750549,2694.082275,659.80481
2,female,5,5,9.00,942.714905,2417.553223,367.564819,2334.558105,752.499695,1022.231079,...,1004.073975,1269.758301,829.196167,5006.84668,1785.66687,1756.018311,902.354553,1322.713379,3709.341064,869.626404
3,female,10,10,14.00,843.530884,2217.308838,301.612610,2045.992676,645.712219,899.347839,...,902.269409,1216.517822,705.296509,4520.147461,1612.52002,1554.21582,806.993469,1081.327026,3341.791992,740.536255
4,female,15,15,19.00,779.912292,2116.948730,236.588181,1660.364990,517.699158,752.166077,...,817.502869,994.991577,682.291016,3536.986572,1261.141357,1251.37085,639.822144,820.000305,2540.56958,632.385742
5,female,20,20,24.00,729.269897,1979.765503,170.792511,1291.625854,414.462524,623.832520,...,744.390686,834.769165,640.306091,2792.485352,984.567505,1013.013794,509.173462,781.731934,1983.347412,561.040894
6,female,25,25,29.00,674.953003,1823.707520,167.816742,1172.003662,382.501465,566.349854,...,676.872314,766.305176,571.848267,2524.393066,879.864929,895.870056,472.338593,706.279297,1833.511841,514.318604
7,female,30,30,34.00,691.011658,1759.175537,161.306030,1156.423584,365.341919,567.117188,...,727.735168,783.109253,570.674438,2411.430664,816.551392,840.785217,446.403931,834.137451,1748.859619,476.913025
8,female,35,35,39.00,646.984741,1659.781128,180.435928,1107.030273,348.028473,556.565918,...,686.334839,742.141174,528.485168,2405.919189,833.367554,844.401794,454.534546,705.550415,1783.333496,444.340454
9,female,40,40,44.00,524.088989,1361.952271,126.148636,909.647766,275.139771,434.523041,...,599.949768,635.800049,453.031616,1818.840332,623.739075,629.527039,336.525452,581.577393,1308.754517,340.873199
10,female,45,45,49.00,434.482605,1182.377686,111.518036,762.321960,232.708069,389.756653,...,493.689209,526.638672,384.095459,1595.600586,540.205383,527.717896,307.208862,422.477905,1172.985352,282.997162
11,female,50,50,54.00,353.727966,984.814453,86.576302,645.818848,199.569122,318.597382,...,418.450531,415.490814,337.149109,1343.924072,422.434204,421.737427,248.369217,308.61261,946.246399,236.358917
12,female,55,55,59.00,298.813049,858.670166,79.410530,582.536865,172.371094,296.302368,...,358.195374,380.280121,314.95752,1256.517334,379.769379,381.255768,235.791656,255.148438,925.695923,202.747757
13,female,60,60,64.00,242.739899,667.587280,65.625351,530.556152,157.693146,269.977722,...,279.60437,303.186584,249.505432,1013.070923,326.171326,314.86792,188.318329,185.172501,720.135986,163.753174
14,female,65,65,69.00,176.233856,544.712341,58.221779,440.228607,125.948807,230.576965,...,234.535919,227.152802,214.310089,1082.031006,316.35144,286.808197,194.047241,132.700714,776.99292,127.874641
15,female,70,70,74.00,113.666733,354.474884,32.626350,304.986145,86.243027,171.050507,...,146.462845,153.037537,136.408798,672.725037,216.13063,190.879837,115.475685,79.393311,475.516998,85.168007
16,female,75,75,79.00,60.945129,196.728470,16.710918,166.034912,47.949894,109.386398,...,77.913773,83.417763,78.080734,348.957062,122.749992,105.265869,59.788685,43.482632,245.702026,44.81662
17,female,80,80,84.00,27.218948,95.171234,8.581465,72.018463,21.482477,64.892075,...,37.055283,37.336311,40.982212,177.169006,61.631947,51.024422,30.708963,23.608768,128.240906,19.467035
18,female,85,85,89.00,10.717461,37.487766,3.614874,25.935791,8.137091,46.014259,...,14.57052,14.351597,17.012455,71.531006,24.739548,19.854937,12.104425,12.568623,52.882965,7.234604
19,female,90,90,1000.00,2.499122,7.334262,0.719920,4.928016,1.687006,30.974676,...,2.893597,3.091261,3.275118,12.693132,5.191412,3.72773,2.012207,4.947841,9.516237,1.417711
20,male,0,0,0.99,173.560242,478.087769,63.907097,425.832703,141.597778,192.824890,...,194.160995,234.829666,160.831299,908.489441,330.090942,322.009644,162.301636,241.91629,668.706299,162.479584
21,male,1,1,4.00,736.349915,2028.339844,271.132751,1806.642212,600.744019,735.482666,...,823.749329,996.290344,682.344238,3854.371094,1397.688721,1366.162354,688.58313,1026.359009,2837.061768,689.337646
22,male,5,5,9.00,983.023682,2529.307617,396.083923,2500.206543,812.076721,1069.698486,...,1033.458496,1311.262695,861.276978,5297.438477,1861.842773,1843.077148,961.589844,1461.714844,3925.430664,914.691528
23,male,10,10,14.00,852.497986,2306.912354,331.290039,2207.483398,701.378723,950.123779,...,929.316406,1240.699585,736.0495,4831.571289,1717.849243,1648.113525,865.678711,1222.458374,3566.83252,783.092896
24,male,15,15,19.00,791.350220,2166.426270,247.632080,1772.399902,538.266479,792.368896,...,846.513672,1046.112793,706.357788,3744.789551,1351.531006,1372.186035,681.335449,957.211182,2716.978516,665.479492
25,male,20,20,24.00,749.847290,2124.524414,164.522568,1417.267212,449.465363,655.855103,...,775.32074,918.761169,699.293823,3023.449219,1149.01709,1211.276855,540.456787,862.307312,2142.620605,607.77063
26,male,25,25,29.00,716.878540,2013.508789,138.447220,1196.167358,395.742676,568.237366,...,693.45636,829.744812,641.582031,2643.503418,991.895142,1065.786377,493.150421,812.395874,1946.596558,575.296997
27,male,30,30,34.00,723.675171,1914.744385,132.139938,1150.352539,378.226654,554.332642,...,701.349487,819.467163,616.657166,2451.911377,907.853516,950.695862,457.632446,903.417786,1789.049561,541.230347
28,male,35,35,39.00,688.300903,1743.993164,131.041199,1035.092285,335.576172,511.366516,...,659.00177,740.679443,550.069092,2299.817871,828.21814,870.072266,438.692108,864.541992,1743.795898,482.733704
29,male,40,40,44.00,561.149292,1432.907227,102.526352,853.109253,271.570465,418.804688,...,600.624268,645.960144,473.060608,1862.483276,676.479736,700.080566,350.226257,782.147217,1394.071289,376.047485
30,male,45,45,49.00,457.487244,1201.435913,98.361351,744.276123,236.145813,374.403503,...,518.990479,531.97052,395.107727,1610.008057,568.718506,577.515198,309.514282,592.945251,1187.120605,313.113464
31,male,50,50,54.00,395.561310,997.973755,73.505806,608.378479,189.367004,290.109863,...,433.951874,429.214539,349.212311,1316.755249,432.073364,425.974243,252.105042,453.9216,954.978638,252.839264
32,male,55,55,59.00,297.834778,863.733215,69.847206,542.341431,163.754669,276.445435,...,358.382599,330.638306,312.756744,1199.584961,384.664612,370.420044,233.377319,328.723053,884.728882,209.121124
33,male,60,60,64.00,243.075958,586.584351,50.237701,396.074097,120.579590,236.667816,...,251.679489,265.130524,218.199814,808.629761,253.835281,255.777756,154.553741,245.564148,574.894531,158.4422
34,male,65,65,69.00,158.323212,408.995789,49.398727,354.737762,105.120712,218.454010,...,167.018219,173.140121,160.008408,700.564514,219.997284,211.778931,134.575058,155.815582,511.167297,108.357414
35,male,70,70,74.00,91.131958,225.480392,27.417465,235.314804,64.667709,151.549057,...,92.917984,95.280586,99.107666,408.491089,134.702606,126.037987,78.294151,83.1875,299.184204,63.909863
36,male,75,75,79.00,41.508957,103.877060,11.932245,117.431389,31.999807,91.213669,...,41.483379,41.02718,47.920212,190.369476,66.883568,60.789989,36.412697,38.01722,140.483444,29.419292
37,male,80,80,84.00,15.321503,42.874664,5.252196,49.645424,14.423381,54.390491,...,15.681183,14.744452,19.220999,82.567719,30.731876,26.589594,15.619992,16.602633,62.504337,11.124106
38,male,85,85,89.00,4.989005,14.404289,1.825735,16.117214,5.087352,37.184116,...,4.968446,4.772076,6.196365,27.704998,11.163352,9.020533,5.014871,7.266304,21.17675,3.4875
39,male,90,90,1000.00,0.889707,2.207148,0.256399,2.190138,0.759123,21.628084,...,0.771139,0.864133,0.908884,3.778298,2.070115,1.272056,0.620089,2.261343,2.869343,0.509205

In [32]:
# excel_path = src_dir / "input_test_egypt.xlsx"
# write_dir = pathlib.Path("/Users/hemert/OneDrive - Stichting Deltares/Documents - International Delta Toolset/Salinity/Vietnam/")
# excel_path = write_dir / 'input.xlsx'
excel_path = "/Users/hemert/OneDrive - Stichting Deltares/Tiaravanni Hermawan's files - Egypt_ERF_data/data_correlation.xlsx"

def write_excel_file(df, excel_path, sheet_name, append=False):
    # Open Excel file
    try:
        # book = load_workbook(excel_path)
        with pd.ExcelWriter(
            excel_path, engine="openpyxl", mode="a", if_sheet_exists="replace"
        ) as writer:
            # excel_file.book = book
            df.to_excel(writer, sheet_name=sheet_name, index=False)
    except Exception as e:
        print(e)
        df.to_excel(excel_path, sheet_name=sheet_name, index=False)

write_excel_file(excel_df, excel_path, sheet_name="rural_gender_demographic")