In [1]:
import dotenv

import rasterio
import geopandas as gpd
import numpy as np
import pandas as pd
import rasterstats

from rasterstats import zonal_stats
from rasterio.warp import reproject, Resampling, calculate_default_transform
from rasterio.mask import mask

from food_security import salinity_correction, water_quality
from food_security.fao_api import FAOClient

from pathlib import Path

In [2]:
from pathlib import Path
import dotenv

print("Current folder:", Path.cwd())
print(".env location:", Path(".env").resolve())
print(".env exists:", Path(".env").exists())

config = dotenv.dotenv_values(".env")
print("Variables found:", config.keys())

Current folder: /Users/hemert/projects/egypt-survey-ml/notebooks
.env location: /Users/hemert/projects/egypt-survey-ml/notebooks/.env
.env exists: True
Variables found: odict_keys(['FAOSTAT_TOKEN', 'FAOSTAT_USERNAME', 'FAOSTAT_PASSWORD'])

In [3]:
config = dotenv.dotenv_values(".env")
username = config["FAOSTAT_USERNAME"]
password = config["FAOSTAT_PASSWORD"]

fao_client = FAOClient(username=username, password=password)

ribasim_run = '95'
include_salinity = False

In [4]:
src_dir = Path('~').expanduser() / f"OneDrive - Stichting Deltares/Tiaravanni Hermawan's files - Egypt_ERF_data/ribasim/{ribasim_run}/"

In [5]:
toml_file = src_dir.parent / f"salinity_correction_egypt_{ribasim_run}.toml"
corrected_df = salinity_correction.generate_crop_yield_csv(
    config_path=toml_file,
    add_labor=False,
    save=False,
    fao_client=fao_client
)

2026-10-21 09:26:43,741 | WARNING  | root | config input salinity_correction.crop_production.path contains a non-existing path
2026-10-21 09:26:43,742 | WARNING  | root | config input salinity_correction.mapping.path contains a non-existing path
2026-10-21 09:26:45,576 | INFO     | food_security.salinity_correction | Starting crop yield correction for Egypt
2026-10-21 09:26:45,578 | INFO     | food_security.salinity_correction | Loaded input data. Areas=61, Crops=31, Years=2

Areas:   0%|          | 0/61 [00:00<?, ?it/s]

/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/egypt-survey-ml/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

In [6]:
relevant_crops = [
    "Bean_FBEAN1 (ha)",
    "LongBerseem_LBSEEM1 (ha)",
    "ShortBerseem_SBSEMW1 (ha)",
    "Cotton_SDELS1 (ha)",
    "SummerMaize_MAIZES1 (ha)",
    "Orchard_CITRUS1 (ha)",
    "LongRice_PADDY1 (ha)",
    "SumerSorghum_SORGMS1 (ha)",
    "SugarBeet_SBEET1 (ha)",
    "SugarCane_SCANE1 (ha)",
    "SumerVegtabl_VEGETS1 (ha)",
    "Wheat_WHEAT1 (ha)",
    "WintrVegtabl_VEGETW1 (ha)",
    "NiliVegetabl_VEGETN1 (ha)",
    "NiliMaize_MAIZEN1 (ha)",
    "Barley_BARLEY1 (ha)",
    "NiliTomato_TMATON1 (ha)",
    "NiliPotato_PTATON1 (ha)",
    "NiliSorghum_SORGMN1 (ha)",
    "SummerTomato_TMATOS1 (ha)",
    "SummerPotato_PTATOS1 (ha)",
    "SummerOnion_ONIONS1 (ha)",
    "WinterTomato_TMATOW1 (ha)",
    "WinterOnion_ONIONW1 (ha)",
    "OtherLegume_OLGUME1 (ha)",
    "Flax_FLAX1 (ha)",
    "Soybean_SBEAN1 (ha)",
    "Lentil_LENTIL1 (ha)",
    "Sesame_SESAME1 (ha)",
    "Peanut_GNUT1 (ha)",
    "WinterPotato_PTATOW1 (ha)"
]

excel_salinity_df = pd.DataFrame(
    {
        "crop_name": corrected_df["crop_name"],
        "crop_name_fao": corrected_df["crop_name_fao"],
        "area": corrected_df["area_map_name"],
        "yield": corrected_df["corrected_yield"] if include_salinity else corrected_df["yield"],
        "cultivation_area (ha)": corrected_df["hectares"],
        "year": corrected_df["year"],
    }
)
    
excel_salinity_df = excel_salinity_df[excel_salinity_df['crop_name'].isin(relevant_crops)]

In [7]:
excel_path = "/Users/hemert/OneDrive - Stichting Deltares/Tiaravanni Hermawan's files - Egypt_ERF_data/data_correlation.xlsx"
if include_salinity:
    new_excel_path = Path(excel_path).with_name(f'data_correlation_{ribasim_run}.xlsx')
else:
    new_excel_path = Path(excel_path).with_name(f'data_correlation_{ribasim_run}_no_salinity.xlsx')
    
def write_excel_file(df, excel_path, sheet_name, append=False):
    # Open Excel file
    try:
        # book = load_workbook(excel_path)
        with pd.ExcelWriter(
            excel_path, engine="openpyxl", mode="a", if_sheet_exists="replace"
        ) as writer:
            # excel_file.book = book
            df.to_excel(writer, sheet_name=sheet_name, index=False)
    except Exception as e:
        print("File does not exist yet, creating new Excel file...")
        df.to_excel(excel_path, sheet_name=sheet_name, index=False)

In [8]:
command_gdf = gpd.read_file(src_dir.parent / 'Final2_Command_Area.shp')
conversion_df = pd.read_excel(excel_path, sheet_name='command_area')

mapping = (
    command_gdf.merge(
        conversion_df[['area_map_name', 'area_name']],
        left_on='OBJECTID',
        right_on='area_map_name'
    )
    .set_index('Name')['area_name']
)

# excel_salinity_df['area'] = excel_salinity_df['area'].map(mapping)

In [9]:
write_excel_file(excel_salinity_df, new_excel_path, sheet_name="production_salinity")

File does not exist yet, creating new Excel file...

In [10]:
pp_df = pd.read_excel(excel_path, sheet_name='farm_gate_price')

excel_crop_df = pd.DataFrame(
    {
        "area": excel_salinity_df["area"].unique()
    }
)

crop_names_fao = excel_salinity_df['crop_name_fao'].unique()
for crop_name_fao in crop_names_fao:
    excel_crop_df[f"salinity_production_{crop_name_fao}"] = 0.0
    excel_crop_df[f"salinity_cultivation_area_{crop_name_fao}"] = 0.0

for i, row in excel_crop_df.iterrows():
    pp_total = 0
    area_name = row["area"]
    salinity_crops_row = excel_salinity_df[(excel_salinity_df['area'] == area_name) & (excel_salinity_df['year'] == 2020)]
    for crop_name_fao in crop_names_fao:
        if crop_name_fao in salinity_crops_row['crop_name_fao'].values:
            salinity_crop_row = salinity_crops_row[salinity_crops_row['crop_name_fao'] == crop_name_fao]
            # if all(salinity_crops_row['crop_name']) not in relevant_crops:
            #     continue
            # print("Crop name", crop_name, "FAO CROP NAME", salinity_crop_row['crop_name_fao'])
            yield_total = salinity_crop_row['yield'].sum()
            excel_crop_df.loc[i, f"salinity_production_{crop_name_fao}"] += yield_total
            excel_crop_df.loc[i, f"salinity_cultivation_area_{crop_name_fao}"] += salinity_crop_row['cultivation_area (ha)'].iloc[0]
    
            pp_row = pp_df[pp_df['crop_name_fao'] == crop_name_fao]
            pp_crop = yield_total * pp_row['Farmgate price2022\n(000 EGP/ton)'].iloc[0]
        else:
            pp_crop = 0
        pp_total += pp_crop
    
    excel_crop_df.loc[i, 'producer_price'] = pp_total

In [11]:
df_ha = pd.read_excel(excel_path, sheet_name='command_area')
excel_crop_df = excel_crop_df.merge(df_ha, left_on='area', right_on='area_name')
excel_crop_df['V'] = excel_crop_df['producer_price'] / excel_crop_df['area_ribasim_ha']
excel_crop_df = excel_crop_df.drop(columns=df_ha.columns)
excel_crop_df

,area,"salinity_production_Beans, dry","salinity_cultivation_area_Beans, dry",salinity_production_Alfalfa for forage,salinity_cultivation_area_Alfalfa for forage,salinity_production_Maize (incl. 0067 and 0068),salinity_cultivation_area_Maize (incl. 0067 and 0068),salinity_production_Lemons and limes,salinity_cultivation_area_Lemons and limes,salinity_production_Sorghum,...,salinity_production_Cotton linters,salinity_cultivation_area_Cotton linters,salinity_production_Soybeans,salinity_cultivation_area_Soybeans,"salinity_production_Rice, paddy","salinity_cultivation_area_Rice, paddy",salinity_production_Linseed,salinity_cultivation_area_Linseed,producer_price,V
0,Blk_Air_20,8.675364e+06,2500.825684,3.050184e+08,3518.860840,3.722225e+07,4393.043457,3.527413e+08,15724.215820,1.426772e+07,...,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.000000,0.000000e+00,0.000000,1.107932e+10,99360.788302
1,Blk_Air_24,4.775980e+04,13.767601,1.602551e+07,184.879196,4.068524e+06,431.384827,3.816486e+06,170.128204,2.406154e+06,...,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.000000,0.000000e+00,0.000000,3.283130e+08,101237.441074
2,Blk_Air_23,1.949162e+05,56.188004,6.209801e+07,716.397095,1.570434e+07,1666.485107,1.518288e+07,676.809998,9.278321e+06,...,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.000000,0.000000e+00,0.000000,1.278806e+09,73490.375849
3,Blk_Air_9,1.108071e+06,319.421021,3.786484e+08,4368.297852,9.635428e+07,10540.892578,1.458291e+08,6500.649414,3.996890e+07,...,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.000000,0.000000e+00,0.000000,9.261659e+09,108039.177897
4,Blk_Air_22,5.125520e+05,147.752090,1.727254e+08,1992.656738,4.394487e+07,4827.899414,7.014246e+07,3126.753662,1.708387e+07,...,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.000000,0.000000e+00,0.000000,4.319843e+09,107837.025545
5,Blk_Air_21,1.600492e+05,46.137001,5.370355e+07,619.553955,1.363414e+07,1445.625854,1.278953e+07,570.121521,8.063330e+06,...,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.000000,0.000000e+00,0.000000,1.100219e+09,83470.087722
6,Blk_Air_26,1.683686e+05,48.535202,5.712923e+07,658.691956,1.449159e+07,1539.259277,1.342841e+07,598.600769,8.513248e+06,...,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.000000,0.000000e+00,0.000000,1.158946e+09,99497.431060
7,Blk_Air_6,4.090825e+05,117.925209,3.255196e+08,3649.129883,8.092628e+07,9510.448242,1.900780e+07,847.314453,2.726148e+07,...,1.397195e+04,1.455867,7.335384e+04,NaN,0.000000e+00,0.000000,0.000000e+00,0.000000,2.735226e+09,122190.125053
8,Blk_Air_25,6.734891e+04,19.414501,2.345542e+07,269.996979,5.936492e+06,635.260437,5.216177e+06,232.522507,3.383912e+06,...,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.000000,0.000000e+00,0.000000,4.556350e+08,99679.498366
9,Blk_Air_7,4.577798e+06,1319.630493,2.551022e+09,28720.289062,8.256136e+08,97396.046875,2.878095e+08,12829.738281,2.136640e+08,...,1.055374e+06,109.969208,1.908497e+06,NaN,0.000000e+00,0.000000,0.000000e+00,0.000000,2.444807e+10,128425.325084
10,Blk_Air_8,1.733340e+06,499.665588,7.485640e+08,8464.573242,2.904094e+08,34274.679688,1.228987e+08,5478.476074,6.395662e+07,...,5.708680e+05,59.484005,8.991303e+05,NaN,0.000000e+00,0.000000,0.000000e+00,0.000000,8.165153e+09,131310.551141
11,Blk_Air_65,4.100851e+05,118.214203,5.861196e+08,6670.009277,2.078047e+08,23315.476562,7.047931e+07,3141.769287,6.375054e+06,...,6.981549e+05,72.747200,7.575094e+06,NaN,1.298538e+05,13.640100,0.000000e+00,0.000000,6.491779e+09,147832.727101
12,Blk_Air_62,2.128967e+05,61.371201,2.289348e+08,2585.261719,8.841977e+07,10429.268555,3.037432e+07,1354.001831,3.075710e+06,...,2.454081e+04,2.557133,4.296852e+06,NaN,0.000000e+00,0.000000,0.000000e+00,0.000000,2.806181e+09,143950.988353
13,Blk_Air_27,2.447362e+05,70.549492,2.466789e+08,2797.791504,9.389245e+07,10838.417969,3.368756e+07,1501.696411,4.484674e+06,...,1.741021e+05,18.141302,3.622344e+06,NaN,1.918946e+04,2.015700,0.000000e+00,0.000000,2.908025e+09,144692.260416
14,Blk_Air_11,3.864917e+05,111.413010,2.251603e+08,2430.358154,4.391076e+07,4438.382812,2.684162e+08,11965.237305,5.907169e+05,...,8.288609e+04,8.636667,7.832852e+04,NaN,2.466632e+04,2.591000,0.000000e+00,0.000000,4.940432e+09,132910.925783
15,Blk_Air_77,5.047100e+05,145.491516,3.156117e+08,3430.954102,6.806182e+07,6875.134277,1.432516e+08,6385.752930,2.247685e+06,...,2.792564e+05,29.098303,1.954824e+05,NaN,7.554976e+04,7.935899,0.000000e+00,0.000000,4.563179e+09,111020.852375
16,Blk_Air_58,2.819183e+06,812.678955,3.020138e+09,34480.808594,1.075720e+09,118581.492188,4.099332e+08,18273.667969,5.713658e+07,...,5.125241e+06,534.046204,2.643995e+07,NaN,6.631460e+05,69.658195,0.000000e+00,0.000000,3.279996e+10,146149.801610
17,Blk_Air_59,3.984799e+05,114.868805,3.788500e+08,4262.908203,8.768439e+07,9744.703125,1.012130e+08,4511.791016,5.390706e+07,...,2.204792e+06,229.737579,7.502528e+04,NaN,1.306186e+06,137.204407,0.000000e+00,0.000000,4.384934e+09,109667.217514
18,Blk_Air_60,6.180327e+05,178.158752,5.973252e+08,6734.400391,1.369673e+08,15469.269531,1.539276e+08,6861.656738,9.755370e+07,...,3.859239e+06,402.129730,0.000000e+00,0.0,2.326040e+06,244.332001,0.000000e+00,0.000000,6.826203e+09,107288.060254
19,Blk_Air_41,3.114965e+06,897.943176,3.539400e+08,3730.834961,5.351912e+07,5538.640625,2.957359e+08,13183.077148,4.233841e+04,...,1.639624e+06,170.847595,1.334598e+04,NaN,3.245373e+07,3409.005371,9.039029e+04,7.946399,7.040031e+09,145392.107109
20,Blk_Air_39,7.345279e+06,2117.405518,7.576663e+08,7942.504395,1.123632e+08,11534.051758,6.770218e+08,30179.726562,0.000000e+00,...,3.886949e+06,405.017059,3.000997e+04,NaN,7.722865e+07,8112.252930,2.032530e+05,17.868399,1.585779e+10,159834.243851
21,Blk_Air_40,1.063818e+07,3066.641357,8.916173e+08,9586.708008,2.341817e+08,25873.058594,7.582829e+08,33802.121094,0.000000e+00,...,3.800342e+06,395.992737,4.640022e+04,NaN,6.825183e+07,7169.310059,1.571308e+05,13.813700,2.367881e+10,152898.729150
22,Blk_Air_52,1.909172e+07,5503.522949,1.754521e+09,18589.675781,3.429363e+08,36714.613281,1.621997e+09,72304.054688,0.000000e+00,...,8.372521e+06,872.410339,8.216148e+04,NaN,1.595092e+08,16755.166016,2.782336e+05,24.460102,4.217539e+10,150885.607448
23,Blk_Air_2,5.697720e+06,1642.467773,6.257942e+08,6591.202148,9.388195e+07,9705.491211,5.319466e+08,23712.681641,3.788341e+04,...,3.025177e+06,315.221100,2.388333e+04,NaN,5.963452e+07,6264.129883,1.617582e+05,14.220500,1.226570e+10,144562.614049
24,Blk_Air_53,9.810131e+06,2827.942139,9.907372e+08,10419.969727,1.640780e+08,17143.666016,8.539286e+08,38065.742188,0.000000e+00,...,4.992514e+06,520.216187,3.941517e+04,NaN,9.741075e+07,10232.221680,2.669530e+05,23.468395,2.117571e+10,162248.602289
25,Blk_Air_1,3.253095e+06,937.761658,3.362430e+08,3525.508789,4.976368e+07,5108.228516,2.991309e+08,13334.416016,0.000000e+00,...,1.772092e+06,184.650665,1.329089e+04,NaN,3.450456e+07,3624.428467,9.001719e+04,7.913599,7.019715e+09,159818.668522
26,Blk_Air_47,2.071271e+06,597.080017,1.288395e+09,14353.804688,2.426131e+08,28624.013672,8.663430e+08,38619.136719,0.000000e+00,...,9.130082e+06,951.347595,1.203355e+05,NaN,1.525640e+08,16025.626953,2.716714e+05,23.883204,2.063919e+10,183124.125464
27,Blk_Air_46,2.039577e+06,587.943787,9.874250e+08,11353.114258,1.807860e+08,21323.316406,3.540689e+08,15783.394531,0.000000e+00,...,9.536616e+06,993.708069,1.112622e+05,NaN,1.636597e+08,17191.148438,3.767809e+05,33.123596,1.330489e+10,160640.553238
28,Blk_Air_43,1.510829e+05,43.552303,1.432441e+08,1549.949707,2.643910e+07,3120.394531,3.397691e+08,15145.952148,0.000000e+00,...,3.524073e+05,36.720570,0.000000e+00,0.0,2.536486e+06,266.437561,0.000000e+00,0.000000,4.916138e+09,204353.725409
29,Blk_Air_44,7.503724e+04,21.630800,7.357125e+07,799.067322,1.314209e+07,1551.055420,1.649828e+08,7354.471680,0.000000e+00,...,2.116612e+05,22.054934,0.000000e+00,0.0,2.677028e+06,281.200378,0.000000e+00,0.000000,2.428098e+09,197085.858948
30,Blk_Air_45,6.945886e+05,200.227325,1.206945e+08,1337.782349,2.167984e+07,2501.741211,3.082983e+08,13743.074219,0.000000e+00,...,1.274016e+06,132.751434,0.000000e+00,0.0,1.361545e+06,143.019470,0.000000e+00,0.000000,4.308041e+09,208339.361457
31,Blk_Air_42,7.829255e+05,225.692001,1.831046e+08,2014.633057,3.317810e+07,3856.677979,4.573033e+08,20385.296875,0.000000e+00,...,1.465212e+06,152.673996,0.000000e+00,0.0,2.432960e+06,255.562973,0.000000e+00,0.000000,6.457582e+09,207079.973087
32,Blk_Air_38,2.806144e+04,8.089200,3.651057e+08,3593.627197,7.928341e+07,9357.181641,1.138693e+08,5075.973145,0.000000e+00,...,0.000000e+00,0.000000,5.434325e+04,NaN,1.097381e+06,115.271088,0.000000e+00,0.000000,3.124455e+09,138225.773098
33,Blk_Air_16,9.475640e+05,273.151917,6.481186e+08,7124.337891,1.257228e+08,14830.804688,1.709705e+08,7621.386230,0.000000e+00,...,4.426364e+06,461.223724,9.024759e+04,NaN,7.728746e+07,8118.430176,1.528083e+05,13.433701,7.172858e+09,152721.237533
34,Blk_Air_48,1.766005e+06,509.081970,7.180305e+08,7911.297852,9.227310e+07,9475.493164,8.270460e+07,3686.738770,0.000000e+00,...,6.501079e+06,677.407471,3.154349e+05,NaN,1.221386e+08,12829.687500,9.807012e+05,86.215500,6.720610e+09,169703.814677
35,Blk_Air_37,8.119264e+04,23.405201,3.163984e+08,3166.903320,6.759396e+07,7977.572754,9.588198e+07,4274.148926,0.000000e+00,...,2.764550e+05,28.806398,4.838035e+04,NaN,5.604716e+06,588.730774,0.000000e+00,0.000000,2.797027e+09,139662.787505
36,Blk_Air_19,4.093637e+06,1180.062500,1.908522e+09,22002.937500,3.459686e+08,40674.812500,4.520403e+08,20150.687500,0.000000e+00,...,1.930517e+07,2011.583496,3.010504e+05,NaN,3.346083e+08,35147.933594,6.796562e+05,59.750000,2.326794e+10,159628.602462
37,Blk_Air_17,2.729190e+06,786.737000,8.380240e+08,9360.756836,8.600628e+07,7730.750977,4.385797e+07,1955.064941,0.000000e+00,...,9.660183e+06,1006.583679,2.452908e+05,NaN,1.828034e+08,19202.035156,1.554041e+06,136.618988,7.877552e+09,172662.468649
38,Blk_Air_50,1.265574e+06,364.824005,3.785643e+08,4213.717285,3.492977e+07,2912.511475,1.123040e+07,500.619598,0.000000e+00,...,4.370036e+06,455.354370,0.000000e+00,NaN,8.356722e+07,8778.070312,7.608099e+05,66.884399,3.397412e+09,177949.500309
39,Blk_Air_49,1.753910e+06,505.595215,5.238686e+08,5837.326660,5.076964e+07,4372.249512,2.042852e+07,910.645935,0.000000e+00,...,6.092816e+06,634.866699,1.394265e+04,NaN,1.159012e+08,12174.502930,1.012986e+06,89.053696,4.814072e+09,168778.601921
40,Blk_Air_12,3.621945e+06,1044.089111,1.075650e+09,11974.944336,1.015152e+08,8574.362305,3.637614e+07,1621.546265,0.000000e+00,...,1.253915e+07,1306.569580,0.000000e+00,NaN,2.390532e+08,25110.632812,2.123175e+06,186.652802,9.703269e+09,174155.885083
41,Blk_Air_51,1.940961e+06,559.515991,7.090450e+08,8020.596680,1.671361e+07,1410.500854,6.515166e+07,2904.278320,0.000000e+00,...,5.402975e+06,562.985840,0.000000e+00,NaN,9.686964e+07,10175.382812,1.302501e+06,114.505600,4.658953e+09,180502.625460
42,Blk_Air_34,1.538710e+06,443.560120,8.446643e+08,9665.638672,1.239355e+08,14246.886719,2.310865e+08,10301.186523,0.000000e+00,...,8.365444e+06,871.672913,2.890886e+05,NaN,1.774791e+08,18642.761719,4.518354e+05,39.721798,1.056130e+10,170390.291755
43,Blk_Air_63,1.631679e+05,47.036003,2.967109e+08,3335.280273,3.565086e+07,4207.583984,4.672434e+08,20828.394531,0.000000e+00,...,2.092875e+06,218.076019,0.000000e+00,0.0,6.435859e+07,6760.355957,0.000000e+00,0.000000,7.872146e+09,188243.293124
44,Blk_Air_14,4.323580e+05,124.634781,1.714280e+08,1949.476318,2.421789e+05,27.631298,1.920225e+07,855.982422,0.000000e+00,...,1.079517e+06,112.484856,3.949512e+03,NaN,1.863177e+07,1957.119141,3.076187e+05,27.043402,9.906191e+08,181531.818253
45,Blk_Air_13,4.168108e+04,12.015301,2.963394e+08,3395.960449,5.042904e+07,5950.850586,2.612080e+07,1164.391602,0.000000e+00,...,0.000000e+00,0.000000,3.669035e+03,NaN,1.039870e+04,1.092300,0.000000e+00,0.000000,1.642775e+09,24981.366149
46,Blk_Air_36,1.195071e+04,3.445000,9.098882e+07,1034.533447,1.572437e+07,1855.821533,9.126967e+06,406.854523,0.000000e+00,...,0.000000e+00,0.000000,1.157176e+03,NaN,1.967784e+04,2.067000,0.000000e+00,0.000000,5.191033e+08,26782.752944
47,Blk_Air_57,2.372012e+05,68.377411,1.324080e+09,15204.203125,2.103491e+08,24742.851562,1.096746e+08,4888.983887,0.000000e+00,...,5.780968e+05,60.237236,1.640569e+04,NaN,1.097320e+07,1152.647461,2.222265e+05,19.536400,7.312095e+09,27124.829394
48,Blk_Air_35,4.256345e+06,1226.965942,1.147201e+09,12883.142578,9.881892e+07,11469.140625,5.437772e+07,2424.005859,0.000000e+00,...,2.838491e+07,2957.686279,1.005214e+05,NaN,2.628873e+08,27614.214844,2.127552e+06,187.037506,1.072006e+10,146858.189524
49,Blk_Air_18,1.231843e+06,355.100433,2.523888e+09,28940.683594,2.488338e+08,28378.441406,1.723747e+08,7683.978027,0.000000e+00,...,9.308612e+06,969.950256,2.319299e+05,NaN,1.540970e+08,16186.657227,3.029450e+06,266.325317,1.450362e+10,65490.021247
50,Blk_Air_30,2.059573e+05,59.370804,9.175898e+08,10473.707031,1.302802e+08,15223.373047,7.999024e+07,3565.740234,0.000000e+00,...,1.106047e+06,115.249222,4.692389e+04,NaN,2.104576e+07,2210.688965,4.369865e+05,38.416401,5.195823e+09,35376.296556
51,Blk_Air_28,9.966993e+04,28.731602,2.032885e+08,2331.250000,1.443386e+07,1583.430542,1.276539e+07,569.045288,0.000000e+00,...,8.374239e+05,87.258934,1.070664e+04,NaN,1.587963e+07,1668.028687,3.268219e+05,28.731602,1.156564e+09,143476.439831
52,Blk_Air_29,9.776336e+03,2.818200,2.184405e+07,250.563583,1.545588e+06,170.116821,1.379360e+06,61.487991,0.000000e+00,...,8.824186e+04,9.194734,2.868586e+03,NaN,1.672357e+06,175.667786,3.594272e+04,3.159800,1.235305e+08,158575.697275
53,Blk_Air_55,1.308976e+06,377.335144,9.816307e+08,11165.692383,7.544437e+07,7752.522949,5.300093e+07,2362.632812,0.000000e+00,...,6.940798e+06,723.225708,1.934861e+05,NaN,1.180538e+08,12400.605469,1.707120e+06,150.076492,6.551259e+09,152223.872794
54,Blk_Air_54,5.333770e+06,1537.552490,1.418650e+09,15925.316406,1.224024e+08,14220.032227,6.313065e+07,2814.186768,0.000000e+00,...,3.574204e+07,3724.293945,1.252034e+05,NaN,3.299203e+08,34655.500000,2.649948e+06,232.962494,1.331798e+10,159441.333384
55,Blk_Air_33,9.861760e+06,2842.824951,2.480364e+09,27654.287109,2.156674e+08,21492.347656,9.415712e+07,4197.259766,0.000000e+00,...,5.108938e+07,5323.474609,0.000000e+00,NaN,6.043279e+08,63479.828125,4.909826e+06,431.633118,2.362774e+10,166597.862679
56,Blk_Air_15,3.536576e+06,1019.480103,1.330799e+09,15042.427734,4.453501e+07,3899.510742,1.114912e+08,4969.964844,0.000000e+00,...,1.037099e+07,1080.648804,0.000000e+00,NaN,1.880916e+08,19757.519531,2.435282e+06,214.090790,9.006829e+09,180493.962262
57,Blk_Air_32,1.029793e+05,29.685600,2.047420e+07,227.908783,1.889150e+06,222.961212,7.626052e+05,33.994797,0.000000e+00,...,6.841509e+05,71.287994,1.608289e+03,NaN,5.998560e+06,630.100769,3.993989e+04,3.511200,2.217976e+08,142177.965322
58,Blk_Air_31,1.015147e+06,292.633789,2.018300e+08,2246.672363,1.862281e+07,2197.900391,7.517587e+06,335.112915,0.000000e+00,...,6.744202e+06,702.740723,1.585414e+04,NaN,5.913240e+07,6211.387695,3.937183e+05,34.612598,2.186430e+09,156050.933828
59,Blk_Air_56,1.019986e+06,294.028809,2.027921e+08,2257.382324,1.871158e+07,2208.377686,7.588886e+06,338.291199,0.000000e+00,...,6.771295e+06,705.563721,1.592972e+04,NaN,5.939924e+07,6239.417480,3.955952e+05,34.777603,2.197060e+09,131089.510942

In [12]:
excel_command_df = pd.read_excel(excel_path, sheet_name='command_unit')

excel_command_df = (
    excel_command_df
    .drop(columns=excel_crop_df.columns.difference(["area"]), errors="ignore")
    .merge(excel_crop_df, on="area", how="left")
)

for column in excel_crop_df.columns:
    if column != "area" and column != 'producer_price' and 'cultivation' not in column and column != 'V':
        excel_command_df[column] = excel_command_df[column] / excel_command_df['rural_population']
    if column == "producer_price":
        excel_command_df[column] = excel_command_df[column] / excel_command_df['arable_km2']

write_excel_file(excel_command_df, new_excel_path, sheet_name='command_unit')

In [13]:
excel_command_df

,area,population,rural_population,gdp,gdp_pc,rwi_mean,rwi_median,rwi_count,fraction_small,fraction_medium,...,salinity_production_Cotton linters,salinity_cultivation_area_Cotton linters,salinity_production_Soybeans,salinity_cultivation_area_Soybeans,"salinity_production_Rice, paddy","salinity_cultivation_area_Rice, paddy",salinity_production_Linseed,salinity_cultivation_area_Linseed,producer_price,V
0,Blk_Air_1,4.886681e+05,17108.839844,1.811264e+08,10586.715591,0.197545,0.2365,88,0.995078,0.000000,...,103.577589,184.650665,0.776843,NaN,2016.767724,3624.428467,5.261443,7.913599,3.925391e+07,159818.668522
1,Blk_Air_2,2.763242e+06,45841.378906,5.287341e+08,11533.990996,0.216681,0.2070,298,0.910322,0.086349,...,65.992272,315.221100,0.520999,NaN,1300.888442,6264.129883,3.528650,14.220500,1.852979e+07,144562.614049
2,Blk_Air_6,4.915848e+05,4863.967773,3.699759e+07,7606.462231,0.007000,0.0195,44,0.994792,0.000000,...,2.872542,1.455867,15.081071,NaN,0.000000,0.000000,0.000000,0.000000,2.428422e+07,122190.125053
3,Blk_Air_7,7.106464e+06,34764.484375,3.965394e+08,11406.450585,0.283193,0.3100,419,0.997206,0.000000,...,30.357836,109.969208,54.897898,NaN,0.000000,0.000000,0.000000,0.000000,2.733348e+07,128425.325084
4,Blk_Air_8,2.160475e+06,11011.501953,1.205868e+08,10950.987090,0.198614,0.2250,127,0.985005,0.000000,...,51.842882,59.484005,81.653740,NaN,0.000000,0.000000,0.000000,0.000000,2.907325e+07,131310.551141
5,Blk_Air_9,2.190786e+06,16442.775391,1.558876e+08,9480.611721,0.427447,0.4110,159,0.996989,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,2.710189e+07,108039.177897
6,Blk_Air_11,1.388451e+06,12873.267578,7.983651e+07,6201.728334,0.112627,0.1860,75,0.874841,0.022872,...,6.438621,8.636667,6.084587,NaN,1.916089,2.591000,0.000000,0.000000,2.371630e+07,132910.925783
7,Blk_Air_12,1.473297e+06,29670.306641,2.880170e+08,9707.248456,0.154353,0.1785,156,0.998664,0.000000,...,422.616057,1306.569580,0.000000,NaN,8056.986094,25110.632812,71.558925,186.652802,2.935667e+07,174155.885083
8,Blk_Air_13,5.196257e+05,2629.852295,5.235418e+07,19907.650637,0.259649,0.2820,37,1.000000,0.000000,...,0.000000,0.000000,1.395149,NaN,3.954099,1.092300,0.000000,0.000000,2.147014e+07,24981.366149
9,Blk_Air_14,6.171839e+05,937.707642,1.483599e+07,15821.547178,0.475200,0.5930,15,0.958333,0.000000,...,1151.229954,112.484856,4.211880,NaN,19869.491485,1957.119141,328.053908,27.043402,3.246090e+07,181531.818253
10,Blk_Air_15,1.333015e+06,20048.804688,1.870627e+08,9330.368856,0.442547,0.4500,128,0.998378,0.000000,...,517.287048,1080.648804,0.000000,NaN,9381.684890,19757.519531,121.467703,214.090790,3.307724e+07,180493.962262
11,Blk_Air_16,1.699336e+06,8360.513672,1.113271e+08,13315.824455,0.327474,0.3220,135,0.998452,0.000000,...,529.436847,461.223724,10.794503,NaN,9244.343952,8118.430176,18.277385,13.433701,2.514407e+07,152721.237533
12,Blk_Air_17,1.251685e+06,20989.121094,1.906020e+08,9080.988346,0.348654,0.3340,133,0.998915,0.000000,...,460.247142,1006.583679,11.686569,NaN,8709.433767,19202.035156,74.040303,136.618988,2.902430e+07,172662.468649
13,Blk_Air_18,4.015592e+06,49926.058594,6.398476e+08,12815.904158,0.360456,0.3525,294,0.993612,0.000000,...,186.447964,969.950256,4.645467,NaN,3086.503929,16186.657227,60.678738,266.325317,2.342347e+07,65490.021247
14,Blk_Air_19,4.546444e+06,54665.816406,6.061417e+08,11088.130147,0.315300,0.2965,420,0.995153,0.000000,...,353.148773,2011.583496,5.507105,NaN,6120.979105,35147.933594,12.432930,59.750000,2.650778e+07,159628.602462
15,Blk_Air_20,1.123988e+06,46472.812500,4.297484e+08,9247.308591,0.021823,0.0400,237,0.012545,0.864247,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,1.920068e+07,99360.788302
16,Blk_Air_21,3.538237e+05,5953.205078,4.023561e+07,6758.646436,0.221543,0.2190,35,0.998155,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,1.379451e+07,83470.087722
17,Blk_Air_22,7.293649e+05,10252.624023,2.008539e+08,19590.486947,0.236597,0.1710,67,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,2.938983e+07,107837.025545
18,Blk_Air_23,3.553117e+05,8300.535156,8.929422e+07,10757.645873,0.085375,0.0725,40,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,1.242721e+07,73490.375849
19,Blk_Air_24,9.079220e+04,3993.915039,2.144084e+07,5368.377731,0.385750,0.4440,8,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,1.613739e+07,101237.441074
20,Blk_Air_25,1.760697e+05,556.520447,3.258000e+06,5854.231791,0.309077,0.3040,13,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,1.670589e+07,99679.498366
21,Blk_Air_26,5.198152e+05,2519.239990,1.092030e+07,4334.761286,0.203182,0.2220,33,0.997921,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,1.637745e+07,99497.431060
22,Blk_Air_27,4.095886e+05,10798.484375,1.367265e+08,12661.638295,0.249140,0.3000,43,0.997305,0.000000,...,16.122824,18.141302,335.449275,NaN,1.777052,2.015700,0.000000,0.000000,2.665574e+07,144692.260416
23,Blk_Air_28,2.755121e+05,4656.809570,6.603537e+07,14180.389508,0.515800,0.4660,25,1.000000,0.000000,...,179.827825,87.258934,2.299136,NaN,3409.981181,1668.028687,70.181512,28.731602,2.413851e+07,143476.439831
24,Blk_Air_29,4.602190e+04,204.397751,2.292321e+06,11215.000420,0.326000,0.3260,2,1.000000,0.000000,...,431.716391,9.194734,14.034331,NaN,8181.876968,175.667786,175.846958,3.159800,2.205031e+07,158575.697275
25,Blk_Air_30,1.416558e+06,19615.894531,2.326197e+08,11858.733788,0.373628,0.3690,113,0.998126,0.000000,...,56.385225,115.249222,2.392136,NaN,1072.893105,2210.688965,22.277162,38.416401,2.205473e+07,35376.296556
26,Blk_Air_31,1.930800e+05,7221.535156,7.689154e+07,10647.534064,0.114478,0.2090,46,0.926282,0.000000,...,933.901429,702.740723,2.195398,NaN,8188.342052,6211.387695,54.520026,34.612598,2.565854e+07,156050.933828
27,Blk_Air_32,3.530875e+04,546.187012,7.904964e+06,14472.999679,0.495400,0.6000,5,1.000000,0.000000,...,1252.594552,71.287994,2.944576,NaN,10982.611031,630.100769,73.124944,3.511200,2.507436e+07,142177.965322
28,Blk_Air_33,1.556568e+06,119940.671875,1.390005e+09,11589.106417,0.130349,0.1380,418,0.990906,0.000000,...,425.955459,5323.474609,0.000000,NaN,5038.556668,63479.828125,40.935455,431.633118,2.723791e+07,166597.862679
29,Blk_Air_34,2.339434e+05,54580.367188,8.911798e+08,16327.844811,-0.252714,-0.3030,213,0.482198,0.495089,...,153.268381,871.672913,5.296568,NaN,3251.701979,18642.761719,8.278351,39.721798,2.249928e+07,170390.291755
30,Blk_Air_35,1.825861e+06,32119.058594,4.258635e+08,13258.904289,0.249291,0.2180,203,0.999654,0.000000,...,883.740534,2957.686279,3.129651,NaN,8184.776376,27614.214844,66.239535,187.037506,2.516946e+07,146858.189524
31,Blk_Air_36,1.703025e+05,482.005341,6.200016e+06,12862.960650,0.249769,0.2390,13,1.000000,0.000000,...,0.000000,0.000000,2.400753,NaN,40.824942,2.067000,0.000000,0.000000,2.187017e+07,26782.752944
32,Blk_Air_37,1.011020e+06,4377.714844,5.640829e+07,12885.327711,0.331950,0.3050,60,0.997661,0.000000,...,63.150527,28.806398,11.051507,NaN,1280.283481,588.730774,0.000000,0.000000,2.224190e+07,139662.787505
33,Blk_Air_38,1.750008e+06,3681.739258,5.573427e+07,15138.028363,0.515373,0.5170,67,0.998957,0.000000,...,0.000000,0.000000,14.760210,NaN,298.060386,115.271088,0.000000,0.000000,2.212244e+07,138225.773098
34,Blk_Air_39,1.101411e+05,72775.585938,6.468130e+08,8887.774050,-0.331303,-0.4000,122,0.017292,0.721118,...,53.410068,405.017059,0.412363,NaN,1061.188955,8112.252930,2.792874,17.868399,3.967688e+07,159834.243851
35,Blk_Air_40,3.181692e+05,120088.914062,1.011916e+09,8426.393345,0.013026,0.0105,274,0.508107,0.397136,...,31.646068,395.992737,0.386382,NaN,568.344152,7169.310059,1.308454,13.813700,3.458534e+07,152898.729150
36,Blk_Air_41,2.225583e+05,38175.875000,3.811912e+08,9985.134425,-0.068388,-0.1200,80,0.234577,0.757807,...,42.949228,170.847595,0.349592,NaN,850.110967,3409.005371,2.367733,7.946399,3.664835e+07,145392.107109
37,Blk_Air_42,2.102774e+04,21027.736328,2.864433e+08,13622.163690,-0.031845,-0.0195,110,0.000000,0.566477,...,69.679980,152.673996,0.000000,0.0,115.702397,255.562973,0.000000,0.000000,4.000185e+07,207079.973087
38,Blk_Air_43,1.094917e+05,10572.814453,1.541786e+08,14582.552150,0.038987,0.0010,78,0.000000,0.572209,...,33.331454,36.720570,0.000000,0.0,239.906367,266.437561,0.000000,0.000000,4.549297e+07,204353.725409
39,Blk_Air_44,1.791276e+05,9324.440430,1.432774e+08,15365.791224,0.143327,0.0690,49,0.001546,0.890263,...,22.699614,22.054934,0.000000,0.0,287.097952,281.200378,0.000000,0.000000,2.854399e+07,197085.858948
40,Blk_Air_45,3.629696e+05,22847.392578,2.122873e+08,9291.534875,0.273190,0.2785,84,0.000000,0.740419,...,55.761965,132.751434,0.000000,0.0,59.593031,143.019470,0.000000,0.000000,2.853673e+07,208339.361457
41,Blk_Air_46,7.024008e+05,68400.140625,7.078949e+08,10349.318905,-0.033854,-0.0370,233,0.827606,0.146476,...,139.423924,993.708069,1.626636,NaN,2392.680929,17191.148438,5.508481,33.123596,2.697985e+07,160640.553238
42,Blk_Air_47,2.740187e+06,66924.351562,8.437958e+08,12608.202376,0.163087,0.1510,299,0.819590,0.074067,...,136.423914,951.347595,1.798082,NaN,2279.648057,16025.626953,4.059380,23.883204,2.899677e+07,183124.125464
43,Blk_Air_48,1.712182e+06,14001.244141,2.006965e+08,14334.192289,0.389033,0.4030,120,0.993452,0.000000,...,464.321523,677.407471,22.529063,NaN,8723.411061,12829.687500,70.043865,86.215500,2.731345e+07,169703.814677
44,Blk_Air_49,5.030711e+05,11046.679688,1.168252e+08,10575.592847,0.230667,0.2545,78,1.000000,0.000000,...,551.551749,634.866699,1.262157,NaN,10491.953354,12174.502930,91.700461,89.053696,2.915539e+07,168778.601921
45,Blk_Air_50,1.318470e+06,7112.273926,8.412577e+07,11828.252019,0.397352,0.3040,54,0.965251,0.000000,...,614.435839,455.354370,0.000000,NaN,11749.719551,8778.070312,106.971397,66.884399,3.072637e+07,177949.500309
46,Blk_Air_51,6.690581e+05,10060.710938,1.046008e+08,10396.955882,0.283716,0.2660,67,1.000000,0.000000,...,537.037097,562.985840,0.000000,NaN,9628.508423,10175.382812,129.464111,114.505600,3.401707e+07,180502.625460
47,Blk_Air_52,1.870498e+06,140708.000000,1.439695e+09,10231.792396,-0.020742,-0.0150,535,0.554925,0.438628,...,59.502807,872.410339,0.583915,NaN,1133.618444,16755.166016,1.977383,24.460102,3.712397e+07,150885.607448
48,Blk_Air_53,2.259675e+06,25153.472656,4.300046e+08,17095.237668,0.085553,0.1060,273,0.941597,0.044631,...,198.482117,520.216187,1.566987,NaN,3872.656207,10232.221680,10.612968,23.468395,3.714395e+07,162248.602289
49,Blk_Air_54,1.499056e+06,47602.515625,6.241390e+08,13111.470340,0.149602,0.1870,256,0.964041,0.000000,...,750.843596,3724.293945,2.630184,NaN,6930.732203,34655.500000,55.668234,232.962494,2.572219e+07,159441.333384
50,Blk_Air_55,1.678027e+06,18332.283203,3.019399e+08,16470.392532,0.340024,0.3290,125,0.985049,0.000000,...,378.610641,723.225708,10.554390,NaN,6439.664863,12400.605469,93.120977,150.076492,2.594129e+07,152223.872794
51,Blk_Air_56,2.089469e+05,21239.603516,2.761340e+08,13000.900525,0.220841,0.1850,44,0.994421,0.000000,...,318.805151,705.563721,0.750001,NaN,2796.626592,6239.417480,18.625355,34.777603,2.090146e+07,131089.510942
52,Blk_Air_57,2.099713e+06,15294.796875,1.552600e+08,10151.166006,0.249282,0.2310,131,0.928385,0.069444,...,37.796955,60.237236,1.072632,NaN,717.446861,1152.647461,14.529552,19.536400,2.157382e+07,27124.829394
53,Blk_Air_58,8.810064e+06,74374.312500,9.367571e+08,12595.169279,0.263209,0.2745,578,0.946679,0.051039,...,68.911440,534.046204,355.498466,NaN,8.916331,69.658195,0.000000,0.000000,2.677942e+07,146149.801610
54,Blk_Air_59,1.006270e+06,26175.203125,2.694352e+08,10293.526911,-0.012456,-0.0105,136,0.939148,0.000000,...,84.232068,229.737579,2.866273,NaN,49.901657,137.204407,0.000000,0.000000,1.284802e+07,109667.217514
55,Blk_Air_60,3.204332e+06,26113.062500,3.221686e+08,12337.448844,0.153388,0.1335,240,0.997475,0.000000,...,147.789598,402.129730,0.000000,0.0,89.075745,244.332001,0.000000,0.000000,1.302092e+07,107288.060254
56,Blk_Air_62,1.178230e+06,13630.004883,1.669893e+08,12251.592448,0.207143,0.1890,98,1.000000,0.000000,...,1.800499,2.557133,315.249520,NaN,0.000000,0.000000,0.000000,0.000000,1.310009e+07,143950.988353
57,Blk_Air_63,3.395640e+04,20529.669922,3.125718e+08,15225.371361,-0.001395,-0.0205,76,0.000000,0.710713,...,101.943931,218.076019,0.000000,0.0,3134.906126,6760.355957,0.000000,0.000000,3.545622e+07,188243.293124
58,Blk_Air_65,1.097516e+06,54401.476562,6.797389e+08,12494.861759,0.050551,0.0560,196,0.989611,0.000000,...,12.833381,72.747200,139.244263,NaN,2.386953,13.640100,0.000000,0.000000,1.320755e+07,147832.727101
59,Blk_Air_77,6.392007e+06,13515.359375,1.397941e+08,10343.349168,0.515766,0.5290,137,0.928644,0.015688,...,20.662149,29.098303,14.463721,NaN,5.589919,7.935899,0.000000,0.000000,1.658747e+07,111020.852375