In [1]:
import dotenv

import rasterio
import geopandas as gpd
import numpy as np
import pandas as pd
import rasterstats

from rasterstats import zonal_stats
from rasterio.warp import reproject, Resampling, calculate_default_transform
from rasterio.mask import mask

from food_security import salinity_correction, water_quality
from food_security.fao_api import FAOClient

from pathlib import Path

In [2]:
from pathlib import Path
import dotenv

print("Current folder:", Path.cwd())
print(".env location:", Path(".env").resolve())
print(".env exists:", Path(".env").exists())

config = dotenv.dotenv_values(".env")
print("Variables found:", config.keys())

Current folder: /Users/hemert/projects/egypt-survey-ml/notebooks
.env location: /Users/hemert/projects/egypt-survey-ml/notebooks/.env
.env exists: True
Variables found: odict_keys(['FAOSTAT_TOKEN', 'FAOSTAT_USERNAME', 'FAOSTAT_PASSWORD'])

In [3]:
config = dotenv.dotenv_values(".env")
username = config["FAOSTAT_USERNAME"]
password = config["FAOSTAT_PASSWORD"]

fao_client = FAOClient(username=username, password=password)

In [4]:
src_dir = Path('~').expanduser() / "OneDrive - Stichting Deltares/Tiaravanni Hermawan's files - Egypt/04_Data/2026_data/"

In [5]:
toml_file = src_dir.parent / "salinity_correction_egypt.toml"
corrected_df = salinity_correction.generate_crop_yield_csv(
    config_path=toml_file,
    add_labor=False,
    save=False,
    fao_client=fao_client
)

2026-09-22 11:39:33,991 | WARNING  | root | config input salinity_correction.crop_production.path contains a non-existing path
2026-09-22 11:39:33,993 | WARNING  | root | config input salinity_correction.mapping.path contains a non-existing path
2026-09-22 11:39:36,552 | INFO     | food_security.salinity_correction | Starting crop yield correction for Egypt
2026-09-22 11:39:36,554 | INFO     | food_security.salinity_correction | Loaded input data. Areas=61, Crops=31, Years=2

Areas:   0%|          | 0/61 [00:00<?, ?it/s]

2026-09-22 11:39:58,786 | INFO     | food_security.salinity_correction | Created dataframe with 2958 rows
2026-09-22 11:39:58,786 | INFO     | food_security.salinity_correction | Crop yield correction finished successfully

In [6]:
corrected_df[corrected_df['year'] == 2020].groupby('crop_name')['corrected_yield'].sum()

crop_name
Barley_BARLEY1 (ha)            193492928.0
Bean_FBEAN1 (ha)               136767248.0
Cotton_SDELS1 (ha)             302305888.0
Flax_FLAX1 (ha)                 29932730.0
Lentil_LENTIL1 (ha)              524607.25
LongBerseem_LBSEEM1 (ha)     36917837824.0
LongRice_PADDY1 (ha)          2927924224.0
NiliMaize_MAIZEN1 (ha)         291084640.0
NiliPotato_PTATON1 (ha)         45409888.0
NiliSorghum_SORGMN1 (ha)        2197268.25
NiliTomato_TMATON1 (ha)        147447728.0
NiliVegetabl_VEGETN1 (ha)      181028032.0
Orchard_CITRUS1 (ha)         12407191552.0
OtherLegume_OLGUME1 (ha)         5209344.0
Peanut_GNUT1 (ha)              147893728.0
Sesame_SESAME1 (ha)             46739824.0
ShortBerseem_SBSEMW1 (ha)     1114145536.0
Soybean_SBEAN1 (ha)             49515880.0
SugarBeet_SBEET1 (ha)        13749307392.0
SugarCane_SCANE1 (ha)        13025608704.0
SumerSorghum_SORGMS1 (ha)      631293312.0
SumerVegtabl_VEGETS1 (ha)     4339902976.0
SummerMaize_MAIZES1 (ha)      4158628608.0
SummerOnion_ONIONS1 (ha)        25946892.0
SummerPotato_PTATOS1 (ha)     1657226368.0
SummerTomato_TMATOS1 (ha)     2241030400.0
Wheat_WHEAT1 (ha)             8053854720.0
WinterOnion_ONIONW1 (ha)      2976937216.0
WinterPotato_PTATOW1 (ha)     3194366720.0
WinterTomato_TMATOW1 (ha)     2768190720.0
WintrVegtabl_VEGETW1 (ha)     3003762176.0
Name: corrected_yield, dtype: object

In [7]:
relevant_crops = [
    "Bean_FBEAN1 (ha)",
    "LongBerseem_LBSEEM1 (ha)",
    "ShortBerseem_SBSEMW1 (ha)",
    "Cotton_SDELS1 (ha)",
    "SummerMaize_MAIZES1 (ha)",
    "Orchard_CITRUS1 (ha)",
    "LongRice_PADDY1 (ha)",
    "SumerSorghum_SORGMS1 (ha)",
    "SugarBeet_SBEET1 (ha)",
    "SugarCane_SCANE1 (ha)",
    "SumerVegtabl_VEGETS1 (ha)",
    "Wheat_WHEAT1 (ha)",
    "WintrVegtabl_VEGETW1 (ha)",
    "NiliVegetabl_VEGETN1 (ha)",
    "NiliMaize_MAIZEN1 (ha)",
    "Barley_BARLEY1 (ha)",
    "NiliTomato_TMATON1 (ha)",
    "NiliPotato_PTATON1 (ha)",
    "NiliSorghum_SORGMN1 (ha)",
    "SummerTomato_TMATOS1 (ha)",
    "SummerPotato_PTATOS1 (ha)",
    "SummerOnion_ONIONS1 (ha)",
    "WinterTomato_TMATOW1 (ha)",
    "WinterOnion_ONIONW1 (ha)",
    "OtherLegume_OLGUME1 (ha)",
    "Flax_FLAX1 (ha)",
    "Soybean_SBEAN1 (ha)",
    "Lentil_LENTIL1 (ha)",
    "Sesame_SESAME1 (ha)",
    "Peanut_GNUT1 (ha)",
    "WinterPotato_PTATOW1 (ha)"
]

excel_salinity_df = pd.DataFrame(
    {
        "crop_name": corrected_df["crop_name"],
        "crop_name_fao": corrected_df["crop_name_fao"],
        "area": corrected_df["area_map_name"],
        "yield": corrected_df["corrected_yield"],
        "cultivation_area (ha)": corrected_df["hectares"],
        "year": corrected_df["year"],
    }
)
    
excel_salinity_df = excel_salinity_df[excel_salinity_df['crop_name'].isin(relevant_crops)]

In [8]:
excel_path = "/Users/hemert/OneDrive - Stichting Deltares/Tiaravanni Hermawan's files - Egypt_ERF_data/data_correlation.xlsx"

def write_excel_file(df, excel_path, sheet_name, append=False):
    # Open Excel file
    try:
        # book = load_workbook(excel_path)
        with pd.ExcelWriter(
            excel_path, engine="openpyxl", mode="a", if_sheet_exists="replace"
        ) as writer:
            # excel_file.book = book
            df.to_excel(writer, sheet_name=sheet_name, index=False)
    except Exception as e:
        print(e)
        df.to_excel(excel_path, sheet_name=sheet_name, index=False)

In [9]:
command_gdf = gpd.read_file(src_dir / 'Final2_Command_Area.shp')
conversion_df = pd.read_excel(excel_path, sheet_name='command_area')

mapping = (
    command_gdf.merge(
        conversion_df[['area_map_name', 'area_name']],
        left_on='OBJECTID',
        right_on='area_map_name'
    )
    .set_index('Name')['area_name']
)

# excel_salinity_df['area'] = excel_salinity_df['area'].map(mapping)

In [10]:
write_excel_file(excel_salinity_df, excel_path, sheet_name="production_salinity")

In [14]:
pp_df = pd.read_excel(excel_path, sheet_name='farm_gate_price')

excel_crop_df = pd.DataFrame(
    {
        "area": excel_salinity_df["area"].unique()
    }
)

crop_names_fao = excel_salinity_df['crop_name_fao'].unique()
for crop_name_fao in crop_names_fao:
    excel_crop_df[f"salinity_production_{crop_name_fao}"] = 0.0
    excel_crop_df[f"salinity_cultivation_area_{crop_name_fao}"] = 0.0

for i, row in excel_crop_df.iterrows():
    pp_total = 0
    area_name = row["area"]
    salinity_crops_row = excel_salinity_df[(excel_salinity_df['area'] == area_name) & (excel_salinity_df['year'] == 2020)]
    for crop_name_fao in crop_names_fao:
        if crop_name_fao in salinity_crops_row['crop_name_fao'].values:
            salinity_crop_row = salinity_crops_row[salinity_crops_row['crop_name_fao'] == crop_name_fao]
            # if all(salinity_crops_row['crop_name']) not in relevant_crops:
            #     continue
            # print("Crop name", crop_name, "FAO CROP NAME", salinity_crop_row['crop_name_fao'])
            yield_total = salinity_crop_row['yield'].sum()
            excel_crop_df.loc[i, f"salinity_production_{crop_name_fao}"] += yield_total
            excel_crop_df.loc[i, f"salinity_cultivation_area_{crop_name_fao}"] += salinity_crop_row['cultivation_area (ha)'].iloc[0]
    
            pp_row = pp_df[pp_df['crop_name_fao'] == crop_name_fao]
            pp_crop = yield_total * pp_row['Farmgate price2022\n(000 EGP/ton)'].iloc[0]
        else:
            pp_crop = 0
        pp_total += pp_crop
    
    excel_crop_df.loc[i, 'producer_price'] = pp_total

In [15]:
excel_crop_df['producer_price'].sum() / 1e9

np.float64(449.86812480214763)

In [16]:
df_ha

NameError: name 'df_ha' is not defined

In [17]:
df_ha = pd.read_excel(excel_path, sheet_name='command_area')
excel_crop_df = excel_crop_df.merge(df_ha, left_on='area', right_on='area_name')
excel_crop_df['V'] = excel_crop_df['producer_price'] / excel_crop_df['area_ribasim_ha']
excel_crop_df = excel_crop_df.drop(columns=df_ha.columns)
excel_crop_df

,area,"salinity_production_Beans, dry","salinity_cultivation_area_Beans, dry",salinity_production_Alfalfa for forage,salinity_cultivation_area_Alfalfa for forage,salinity_production_Maize (incl. 0067 and 0068),salinity_cultivation_area_Maize (incl. 0067 and 0068),salinity_production_Lemons and limes,salinity_cultivation_area_Lemons and limes,salinity_production_Sorghum,...,salinity_production_Cotton linters,salinity_cultivation_area_Cotton linters,salinity_production_Soybeans,salinity_cultivation_area_Soybeans,"salinity_production_Rice, paddy","salinity_cultivation_area_Rice, paddy",salinity_production_Linseed,salinity_cultivation_area_Linseed,producer_price,V
0,Blk_Air_20,8.675364e+06,2500.825684,2.763528e+08,3518.860840,2.198723e+07,4393.043457,3.527413e+08,15724.215820,1.426772e+07,...,0.000000e+00,0.000000,0.000000,0.0,0.000000e+00,0.000000,0.000000e+00,0.000000,1.031696e+10,92523.840839
1,Blk_Air_24,4.775980e+04,13.767601,1.378148e+07,184.879196,2.501516e+06,431.384827,3.816486e+06,170.128204,2.406154e+06,...,0.000000e+00,0.000000,0.000000,0.0,0.000000e+00,0.000000,0.000000e+00,0.000000,2.924743e+08,90186.337918
2,Blk_Air_23,1.949162e+05,56.188004,5.339614e+07,716.397095,9.657087e+06,1666.485107,1.518288e+07,676.809998,9.278321e+06,...,0.000000e+00,0.000000,0.000000,0.0,0.000000e+00,0.000000,0.000000e+00,0.000000,1.139834e+09,65503.926725
3,Blk_Air_9,1.108071e+06,319.421021,3.291416e+08,4368.297852,5.839739e+07,10540.892578,1.458291e+08,6500.649414,3.996890e+07,...,0.000000e+00,0.000000,0.000000,0.0,0.000000e+00,0.000000,0.000000e+00,0.000000,8.311494e+09,96955.312388
4,Blk_Air_22,5.125520e+05,147.752090,1.511533e+08,1992.656738,2.622337e+07,4827.899414,7.014246e+07,3126.753662,1.708387e+07,...,0.000000e+00,0.000000,0.000000,0.0,0.000000e+00,0.000000,0.000000e+00,0.000000,3.873180e+09,96686.891462
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,Blk_Air_15,3.536576e+06,1019.480103,1.323370e+09,15042.427734,3.084824e+07,3899.510742,1.114912e+08,4969.964844,0.000000e+00,...,1.037099e+07,1080.648804,227137.640625,NaN,1.559088e+08,19757.519531,2.435282e+06,214.090790,8.331386e+09,166958.295491
57,Blk_Air_32,1.029793e+05,29.685600,2.036714e+07,227.908783,9.082694e+05,222.961212,7.626052e+05,33.994797,0.000000e+00,...,6.841509e+05,71.287994,1608.289062,NaN,3.819775e+06,630.100769,3.993989e+04,3.511200,1.795368e+08,115087.677228
58,Blk_Air_31,1.015147e+06,292.633789,1.965581e+08,2246.672363,8.142934e+06,2197.900391,7.517587e+06,335.112915,0.000000e+00,...,6.744202e+06,702.740723,15854.142578,NaN,3.508066e+07,6211.387695,3.937183e+05,34.612598,1.719966e+09,122758.277168
59,Blk_Air_56,1.019986e+06,294.028809,1.993157e+08,2257.382324,4.463104e+06,2208.377686,7.588886e+06,338.291199,0.000000e+00,...,6.771295e+06,705.563721,15929.720703,NaN,2.343424e+07,6239.417480,3.955952e+05,34.777603,1.490266e+09,88918.036467
60,Blk_Air_78,1.165015e+05,33.583599,0.000000e+00,0.000000,0.000000e+00,0.000000,4.736965e+06,211.160599,1.916013e+05,...,0.000000e+00,0.000000,0.000000,0.0,0.000000e+00,0.000000,0.000000e+00,0.000000,6.711194e+07,NaN

In [25]:
excel_command_df = pd.read_excel(excel_path, sheet_name='command_unit')

excel_command_df = (
    excel_command_df
    .drop(columns=excel_crop_df.columns.difference(["area"]), errors="ignore")
    .merge(excel_crop_df, on="area", how="left")
)

for column in excel_crop_df.columns:
    if column != "area" and column != 'producer_price' and 'cultivation' not in column and column != 'V':
        excel_command_df[column] = excel_command_df[column] / excel_command_df['rural_population']
    if column == "producer_price":
        excel_command_df[column] = excel_command_df[column] / excel_command_df['arable_km2']

write_excel_file(excel_command_df, excel_path, sheet_name='command_unit')

In [43]:
excel_salinity_df[excel_salinity_df['crop_name_fao'] == 'Sugar cane']

,crop_name,crop_name_fao,area,yield,cultivation_area (ha),year
10,SugarCane_SCANE1 (ha),Sugar cane,Blk_Air_20,3643662848.0,39991.08,2020
11,SugarCane_SCANE1 (ha),Sugar cane,Blk_Air_20,-0.0,39991.08,2021
48,SugarCane_SCANE1 (ha),Sugar cane,Blk_Air_24,135372256.0,1449.2037,2020
49,SugarCane_SCANE1 (ha),Sugar cane,Blk_Air_24,-0.0,1449.2037,2021
88,SugarCane_SCANE1 (ha),Sugar cane,Blk_Air_23,526031808.0,5632.8467,2020
...,...,...,...,...,...,...
2815,SugarCane_SCANE1 (ha),Sugar cane,Blk_Air_32,-0.0,0.1596,2021
2858,SugarCane_SCANE1 (ha),Sugar cane,Blk_Air_31,145007.328125,1.5733,2020
2859,SugarCane_SCANE1 (ha),Sugar cane,Blk_Air_31,-0.0,1.5733,2021
2902,SugarCane_SCANE1 (ha),Sugar cane,Blk_Air_56,148261.609375,1.5807998,2020
2903,SugarCane_SCANE1 (ha),Sugar cane,Blk_Air_56,-0.0,1.5807998,2021

In [13]:
(excel_command_df["salinity_production_Alfalfa for forage"] * excel_command_df['rural_population']).sum() / 1e9

np.float64(38.031988464)

In [19]:
(excel_command_df['producer_price'] * excel_command_df['arable_km2']).sum() / 1e9

np.float64(449.8010128575873)

In [23]:
excel_command_df['producer_price']

0     3.753528e+07
1     1.683540e+07
2     2.204309e+07
3     2.479488e+07
4     2.605181e+07
5     2.432148e+07
6     2.342535e+07
7     2.825974e+07
8     2.027190e+07
9     2.781377e+07
10    3.059670e+07
11    1.890700e+07
12    2.803829e+07
13    2.245160e+07
14    2.304212e+07
15    1.787950e+07
16    1.216753e+07
17    2.635098e+07
18    1.107670e+07
19    1.437583e+07
20    1.518710e+07
21    1.543177e+07
22    2.338175e+07
23    2.297170e+07
24    2.130130e+07
25    2.057758e+07
26    2.018442e+07
27    2.029675e+07
28    2.031250e+07
29    1.292055e+07
30    2.238926e+07
31    2.086961e+07
32    1.940105e+07
33    1.932860e+07
34    3.904859e+07
35    3.322422e+07
36    3.632836e+07
37    3.747165e+07
38    4.463743e+07
39    2.749616e+07
40    2.779588e+07
41    2.169430e+07
42    2.703436e+07
43    2.535653e+07
44    2.822858e+07
45    2.914172e+07
46    3.067874e+07
47    3.572390e+07
48    3.564413e+07
49    2.308390e+07
50    1.718764e+07
51    1.417747e+07
52    1.905045e+07
53    2.353149e+07
54    9.874850e+06
55    9.714749e+06
56    1.215864e+07
57    2.766092e+07
58    1.120991e+07
59    1.591693e+07
Name: producer_price, dtype: float64